apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-volume
  namespace: mongodb
  labels:
    app: mongodb
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: db-disk
    fsType: ext4