apiVersion: v1
kind: Service
metadata:
  labels:
    app: express-mongo
  name: express-mongo
  namespace: mongodb
spec:
  type: LoadBalancer
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081 
    name: http
  selector:
    app: express-mongo
